name: CI/CD test-application

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

env:
  REGISTRY: cr.yandex
  REGISTRY_ID: ${{ secrets.YC_REGISTRY_ID }}
  IMAGE_NAME: test-application

jobs:
  # -------------------------------
  # BUILD & PUSH
  # -------------------------------
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "TAG=${GITHUB_REF_NAME}" >> "$GITHUB_ENV"
          else
            echo "TAG=latest" >> "$GITHUB_ENV"
          fi

      - name: Login to Yandex Container Registry
        env:
          YC_TOKEN: ${{ secrets.YC_TOKEN }}
        run: |
          echo "$YC_TOKEN" | docker login "$REGISTRY" -u oauth --password-stdin

      - name: Build and push image
        run: |
          IMAGE="$REGISTRY/$REGISTRY_ID/$IMAGE_NAME:$TAG"
          echo "Building image: $IMAGE"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"


  # -------------------------------
  # DEPLOY
  # -------------------------------
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy on k8s master over SSH
        env:
          K8S_MASTER_HOST: ${{ secrets.K8S_MASTER_HOST }}
        run: |
          IMAGE="$REGISTRY/$REGISTRY_ID/$IMAGE_NAME:${GITHUB_REF_NAME}"
          echo "Deploying image: $IMAGE"

          ssh -o StrictHostKeyChecking=no ubuntu@"$K8S_MASTER_HOST" \
            "sudo -i bash -lc ' \
               export KUBECONFIG=/root/.kube/config; \
               kubectl -n default set image deployment/test-application \
                 test-application=$IMAGE; \
               kubectl -n default rollout status deployment/test-application -n default; \
             '"
