name: CI/CD test-application

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

env:
  REGISTRY_ID: ${{ secrets.YC_REGISTRY_ID }}
  IMAGE_NAME: test-application
  REGISTRY: cr.yandex

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: |
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            TAG="${GITHUB_REF_NAME}"
          else
            TAG="latest"
          fi
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"

      - name: Login to Yandex Container Registry
        run: |
          echo "${{ secrets.YC_REGISTRY_TOKEN }}" | docker login $REGISTRY -u oauth --password-stdin

      - name: Build and push image
        run: |
          IMAGE="$REGISTRY/$REGISTRY_ID/$IMAGE_NAME:${{ steps.vars.outputs.TAG }}"
          echo "Building image: $IMAGE"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

  deploy:
  needs: build-and-push
  runs-on: ubuntu-latest
  # деплой только при теге
  if: startsWith(github.ref, 'refs/tags/')

  steps:
    - name: Deploy to Kubernetes via SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.K8S_MASTER_IP }}      # IP мастер-ноды
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}      # твой id_ed25519 (приватный) из secret
        port: 22
        script: |
          TAG="${GITHUB_REF##*/}"
          REGISTRY_ID="${{ secrets.YC_REGISTRY_ID }}"

          sudo -i << 'EOF'
          TAG="${TAG}"
          REGISTRY_ID="${REGISTRY_ID}"

          kubectl -n default set image deployment/test-application \
            test-application=cr.yandex/${REGISTRY_ID}/test-application:${TAG}

          kubectl -n default rollout status deployment/test-application
          EOF

            "
