name: CI/CD test-application

on:
  push:
    branches:
      - main
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY_ID: ${{ secrets.YC_REGISTRY_ID }}
  IMAGE_NAME:  test-application
  REGISTRY:    cr.yandex

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        id: vars
        run: |
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            TAG="${GITHUB_REF_NAME}"
          else
            TAG="latest"
          fi
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"

      - name: Login to Yandex Container Registry
        run: |
          echo "${{ secrets.YC_REGISTRY_TOKEN }}" | docker login $REGISTRY -u oauth --password-stdin

      - name: Build and push image
        run: |
          IMAGE="$REGISTRY/$REGISTRY_ID/$IMAGE_NAME:${{ steps.vars.outputs.TAG }}"
          echo "Building image: $IMAGE"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

  deploy:
    needs: build-and-push
    if: github.ref_type == 'tag'      # деплой только при теге vX.Y.Z
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Kubernetes via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.K8S_MASTER_IP }}
          username: ubuntu
          key: ${{ secrets.K8S_SSH_KEY }}
          script: |
            TAG="${GITHUB_REF_NAME}"
            IMAGE="cr.yandex/${{ secrets.YC_REGISTRY_ID }}/test-application:${TAG}"

            echo "Using image: $IMAGE"

            # Переходим в root и выполняем kubectl
            sudo -i bash -c "
              export KUBECONFIG=/root/.kube/config
              kubectl set image deployment/test-application test-application=${IMAGE} -n default
              kubectl rollout status deployment/test-application -n default
            "
